### ISSUE TITLE
Admin customer grid breaks when customer has multiple different statuses

### ISSUE THREAD

**Issue by LauHypershop** [Datatrics/magento2-integration#36] opened 2023-03-13 12:18 UTC
**Describe the bug**

**Used versions**
- magento/product-community-edition 2.4.4-p2
- datatrics/magento2-integration 1.6.0 

**To Reproduce**
* Make a customer account in an install with multiple stores. 
* Place orders (or do something else.. not clear on this) in multiple stores so that the customer will have multiple entries in the datatrics_profile table.
* Run the Datatrics\Connect\Model\Cron\ProfileUpdate cron, with (not sure how this happens, but it does) the result that some of the rows for a single customer end up as Synced and some as Errror (or Queued for Update).
* In the admin, go to the customers grid and browse/filter until that user should be featured in the grid. 

**Expected behavior**
The admin frontend renders normally. (Not sure what should be shown in the datatrics sync status field since there are multiple values.)

**Actual behavior**
You get a popup with "Attention; Something went wrong". The page may be stuck with a loading spinner forever (until you reset ui_bookmarks for that user).

In system.log there is an error message:

> [2023-03-13T12:13:10.615938+00:00] main.CRITICAL: Exception: Item (Magento\Customer\Ui\Component\DataProvider\Document) with the same ID "172864" already exists. in (...)/vendor/magento/framework/Data/Collection.php:410

**Screenshots**

![Screenshot 2023-03-13 at 13 14 07](https://user-images.githubusercontent.com/81677770/224698703-5128bfef-4104-4b91-a064-39fec49c1d2e.png)

<img width="1143" alt="Screenshot 2023-03-13 at 13 15 10" src="https://user-images.githubusercontent.com/81677770/224698855-7a708c14-a57d-4cf6-8e4a-f3f2632ff27c.png">

**Additional context**
The error seems to happen in vendor/datatrics/magento2-integration/Plugin/CustomerGridCollection.php which adds multiple "status" items for each distinct profile sync status linked to the user, but that field will only take one entry.

**Comment by Frank-Magmodules** [comment] 2023-03-16 11:19
Thank you for opening this issue @LauHypershop ! We are not able to reproduce this within the [latest version](https://github.com/Datatrics/magento2-integration/releases/tag/v1.6.5) of the plugin. Nevertheless, we appreciate your detailed steps to reproduce the issue and we are currently working closely with the Datatrics team to replicate the issue exactly as you experienced it. 

Rest assured that we are committed to finding a resolution to this issue and we will keep you updated on our progress.

**Comment by Frank-Magmodules** [comment] 2023-05-02 14:35
Hello @LauHypershop, I apologize for keeping you waiting, but I am glad to inform you that we have resolved this issue in the latest release, version [1.6.6](https://github.com/Datatrics/magento2-integration/releases/tag/v1.6.6). Thank you very much for bringing this to our attention and for your patience. We will be closing this issue for now, but please feel free to reopen it if you encounter any further problems or have any additional questions. Thank you.

**Closed as completed** 2023-05-02 14:37 UTC

**Comment by LauHypershop** [comment] 2023-05-04 07:33
Hi Frank,

Thank you for letting us know. I'll make a note to grab this one in the
next round of updates for this client.

With kind regards,


*Lau Bannenberg*
Magento Developer



Magento E-Commerce Specialist

HYPR
Laan van Vredenoord 29
2289 DA Rijswijk
*T: *070 - 217 1220
www.hypershop.nl
