### ISSUE TITLE
In customer admin, email filter is broken again in 1.3.2

### ISSUE THREAD

**Issue by evs-xsarus** [Datatrics/magento2-integration#17] opened 2021-06-07 15:02 UTC
**Describe the bug**
In the customer admin, it's not possible to search on an emailaddress.

Previous bug: https://github.com/Datatrics/magento2-integration/issues/8

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.4
- *Open source/Commerce/B2B*: Commerce
- *Module version number (Check configuration)*: 1.3.2

**To Reproduce**
1. Go to 'admin > customers'
2. Click on 'filter'
3. Specify an e-mailaddress to filter on
4. Click on 'Apply filters'
5. See error

**Expected behavior**
The customers with that emailaddress must be shown.

**Actual behavior**
The following error is shown:

> Something went wrong with processing the default view and we have restored the filter to its original state.

**Screenshots**

**Additional context**
I found this in the logs:

```
[2021-06-07 14:52:51] report.CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'email' in where clause is ambiguous, query was: SELECT COUNT(*) FROM `customer_grid_flat` AS `main_table`
 LEFT JOIN `datatrics_profile` ON datatrics_profile.customer_id = main_table.entity_id WHERE (`email` LIKE '%xsarus.nl%') {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'email' in where clause is ambiguous, query was: SELECT COUNT(*) FROM `customer_grid_flat` AS `main_table`
```

This bug was fixed before in v1.2.0 but reintroduced in v1.3.2. See:

Fix in v1.2.0: https://github.com/Datatrics/magento2-integration/commit/c01749ef6d1381e22e688a2a3cb1a97424142b16#diff-b1e3b9b11af3d78bfa83e7bc3af192d3495440153e99c80f0e88fe4b9c6e1116
Regression in v1.3.2: https://github.com/Datatrics/magento2-integration/commit/3f8fb5a860c75dfc9c72d0be49e1cd51e5c0e140

Why has this been changed as it is now and can it be reverted.

**Comment by Frank-Magmodules** [comment] 2021-06-10 14:09
Hi @evs-xsarus, thank you for opening this issue, this logic was indeed changed between 1.2.0 and 1.3.2. 
The reason for this is that the fix implemented in 1.2.0 did fix it, but partial. 

We have just released the [1.3.5](https://github.com/Datatrics/magento2-integration/releases/tag/v1.3.5) release that should fix it once and for all. This issue looks easy on the surface, but it was pretty complicated to apply a stable solution that works in different scenarios. Also, this issue was not reproducible in a vanilla Magento installation.

We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed as completed** 2021-06-10 14:10 UTC
