### ISSUE TITLE
'entity_id' column isn't found when performing  setup:upgrade

### ISSUE THREAD

**Issue by yuriichayka** [Datatrics/magento2-integration#2] opened 2021-01-21 14:57 UTC
setup:upgrade fails when trying to install the module.
Following error appears:
_SQLSTATE[42S22]: Column not found: 1054 Unknown column 'catalog_product_entity_int.entity_id' in 'field list', query was: SELECT DISTINCT  `catalog_product_entity_int`.`entity_id` FROM `catalog_product_entity_int`
 LEFT JOIN `eav_attribute` ON eav_attribute.attribute_id = catalog_product_entity_int.attribute_id WHERE (value IN (1, 2, 3, 4)) AND (attribute_code = 'visibility') AND (store_id IN (0))_

Magento versions - 2.3.5-p1 EE.

**The problem appears for Enterprise edition only as I understand, due to Magento_Staging module.** 
With such module, there is no `catalog_product_entity_int.entity_id` column.
Instead, there is `row_id` column. 

So, the logic in following file should be fixed:
Datatrics/Connect/Service/ProductData/Filter.php

Probably somewhere else. 

ER: the module is compatible with Magento EE, enabled Magento_Staging module in particular.

**Comment by Marvin-Magmodules** [comment] 2021-01-22 12:17
Hi @yuriichayka, thank you for opening this issue. This is indeed a compatibility issue with Magento Commerce (EE) and content staging due to differences in the primary. We have reproduced this issue on a vanilla 2.3.5-p1 EE instance and are working on getting this compatible. Fix will be implemented in the upcoming 1.0.2 release.

**Comment by Marvin-Magmodules** [comment] 2021-01-25 18:09
Hi @yuriichayka, we are happy to share that we've just released the new [v1.0.2](https://github.com/Datatrics/magento2-integration/releases/tag/v1.0.2) version with a fix for this issue. Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed as completed by Marvin-Magmodules** 2021-01-25 18:09 UTC
